feat: :sparkles: docusaurus migration
eesast/THUAI7 pull request #192
Opened 2024-04-08 03:30 UTC by Panxuc

- [x] 您的代码是否能够编译通过？
- [x] 您是否检查了目前在 [pull requests](https://github.com/eesast/THUAI7/pulls) 中是否有与你的贡献功能相同的更改？
- [x] 您的贡献是否符合[贡献者代码协议](https://github.com/eesast/THUAI7/blob/dev/CODE_OF_CONDUCT.md)？
- [x] 您的贡献是否符合[开发规则](https://github.com/eesast/THUAI7#%E5%BC%80%E5%8F%91%E8%A7%84%E5%88%99)？  

Descriptions of this pull request:

The docs are still outdated and need to be updated

2024-04-08 10:12 UTC, duskmoon314 requested changes

2024-04-08 10:12 UTC, duskmoon314 commented on .github/workflows/deploy.yml
> +    #   - main
不用的触发条件删除吧

2024-04-08 10:12 UTC, duskmoon314 commented on .github/workflows/deploy.yml
> +    permissions:
前面添加后这里可以删除

2024-04-08 10:12 UTC, duskmoon314 commented on .github/workflows/deploy.yml
> +      group: ${{ github.workflow }}-${{ github.ref }}
添加 env

```yaml
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
```

2024-04-08 10:12 UTC, duskmoon314 commented on .github/workflows/deploy.yml
> +      - name: Deploy
用 github 的 action 上传构建产物，path 需要你看着调整一下

```yaml
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
```

2024-04-08 11:17 UTC, DragonAura approved these changes

2024-04-09 02:51 UTC, duskmoon314 commented on docs/README.md
> +  + 半角的括号 `()`、`[]`、`{}`、`<>` 等在左半括号前加空格、右半括号后加空格，除非其空格处紧跟全角标点符号或位于行首或行尾。例如：`Tsinghua University (THU) and Peking University (PKU)（我是全角括号）`
这里改了啥？

2024-04-09 02:52 UTC, duskmoon314 commented on docs/docs/intro/guide.md
> +<!-- ## 我应该如何游玩 THUAI7？
全都注释掉了？

2024-04-09 03:03 UTC, Panxuc commented on docs/README.md
> +  + 半角的括号 `()`、`[]`、`{}`、`<>` 等在左半括号前加空格、右半括号后加空格，除非其空格处紧跟全角标点符号或位于行首或行尾。例如：`Tsinghua University (THU) and Peking University (PKU)（我是全角括号）`
不知道改了啥（）

2024-04-09 03:04 UTC, Panxuc commented on docs/docs/intro/guide.md
> +<!-- ## 我应该如何游玩 THUAI7？
有点过时，打算有时间重新写一遍

2024-04-09 03:10 UTC, duskmoon314 approved these changes

2024-04-09 03:17 UTC, merged