fix small bugs
eesast/THUAI7 pull request #195
Opened 2024-04-09 15:03 UTC by GuoWQ222

- [ ] 您的代码是否能够编译通过？
- [ ] 您是否检查了目前在 [pull requests](https://github.com/eesast/THUAI7/pulls) 中是否有与你的贡献功能相同的更改？
- [ ] 您的贡献是否符合[贡献者代码协议](https://github.com/eesast/THUAI7/blob/dev/CODE_OF_CONDUCT.md)？
- [ ] 您的贡献是否符合[开发规则](https://github.com/eesast/THUAI7#%E5%BC%80%E5%8F%91%E8%A7%84%E5%88%99)？  

Descriptions of this pull request:

No additional description.

2024-04-09 15:51 UTC, Panxuc approved these changes

2024-04-09 15:54 UTC, asdawej requested changes
`Recycle` 应当需要相同的检查.

2024-04-09 15:56 UTC, Panxuc commented
> `Recycle` 应当需要相同的检查.

理论上，如果 `Ship` `IsRemoved`，那么它们根本不可能在能触发这些动作的物体旁边，自然不可能触发这些动作。所以只要逻辑足够完备，不用检查 `IsRemoved` 也可以（）

不过加上也不错

2024-04-10 03:33 UTC, GuoWQ222 commented
修复了已知问题，Repair已不在Rpcservices中，应已被Recover替代

2024-04-10 03:46 UTC, asdawej approved these changes

2024-04-10 03:46 UTC, merged