fix: :sparkles: Add RepairHome and RepairWormhole
eesast/THUAI7 pull request #366
Opened 2024-05-11 15:16 UTC by sigureling

- [ ] 您的代码是否能够编译通过？
- [ ] 您是否检查了目前在 [pull requests](https://github.com/eesast/THUAI7/pulls) 中是否有与你的贡献功能相同的更改？
- [ ] 您的贡献是否符合[贡献者代码协议](https://github.com/eesast/THUAI7/blob/dev/CODE_OF_CONDUCT.md)？
- [ ] 您的贡献是否符合[开发规则](https://github.com/eesast/THUAI7#%E5%BC%80%E5%8F%91%E8%A7%84%E5%88%99)？  

Descriptions of this pull request:

No additional description.

2024-05-11 15:18 UTC, DragonAura requested changes
等初赛结束之后再更新吧）

2024-05-15 14:43 UTC, DragonAura submitted a review, later dismissed

2024-05-15 16:48 UTC, Timothy-Liuxf requested changes

2024-05-15 16:48 UTC, Timothy-Liuxf commented on CAPI/cpp/API/include/structures.h
> +    struct Construction
```suggestion
    struct ConstructionState
```
这个名字更好

2024-05-15 16:48 UTC, Timothy-Liuxf commented on CAPI/cpp/API/include/structures.h
> +        static Construction newConstruction(std::pair<int32_t, int32_t> teamHP, ConstructionType type)
呃，为什么不写成构造函数……

2024-05-15 17:15 UTC, DragonAura submitted a review, later dismissed

2024-05-16 04:19 UTC, Timothy-Liuxf requested changes

2024-05-16 04:19 UTC, Timothy-Liuxf commented on CAPI/cpp/API/src/API.cpp
> +    return std::move(logic.GetConstructionState(cellX, cellY));
`return` 后面不能用 `std::move`，会影响 [RVO（return value optimization）](https://timothy-liuxf.github.io/tm-blogs/blogs/zh-CN/c_cpp/return-value-optimization.html)

2024-05-16 04:19 UTC, Timothy-Liuxf commented on CAPI/cpp/API/src/API.cpp
> +    return std::move(logic.GetConstructionState(cellX, cellY));
这里也是

2024-05-16 04:19 UTC, Timothy-Liuxf commented on CAPI/cpp/API/src/DebugAPI.cpp
> +    return std::move(logic.GetConstructionState(cellX, cellY));
这里也是

2024-05-16 04:19 UTC, Timothy-Liuxf commented on CAPI/cpp/API/src/DebugAPI.cpp
> +    return std::move(logic.GetConstructionState(cellX, cellY));
这里

2024-05-16 04:19 UTC, Timothy-Liuxf commented on CAPI/cpp/API/src/logic.cpp
> +        return std::make_optional<THUAI7::ConstructionState>(THUAI7::ConstructionState(currentState->mapInfo->factoryState[pos], THUAI7::ConstructionType::Factory));
```suggestion
        return std::make_optional<THUAI7::ConstructionState>(currentState->mapInfo->factoryState[pos], THUAI7::ConstructionType::Factory);
```
`make_optional` 直接写构造函数的参数；显式调用构造函数会导致多一次对象的构造。

2024-05-16 04:19 UTC, Timothy-Liuxf commented on CAPI/cpp/API/src/logic.cpp
> +        return std::make_optional<THUAI7::ConstructionState>(THUAI7::ConstructionState(currentState->mapInfo->communityState[pos], THUAI7::ConstructionType::Community));
```suggestion
        return std::make_optional<THUAI7::ConstructionState>(currentState->mapInfo->communityState[pos], THUAI7::ConstructionType::Community);
```

2024-05-16 04:19 UTC, Timothy-Liuxf commented on CAPI/cpp/API/src/logic.cpp
> +        return std::make_optional<THUAI7::ConstructionState>(THUAI7::ConstructionState(currentState->mapInfo->fortState[pos], THUAI7::ConstructionType::Fort));
```suggestion
        return std::make_optional<THUAI7::ConstructionState>(currentState->mapInfo->fortState[pos], THUAI7::ConstructionType::Fort);
```

2024-05-16 04:19 UTC, Timothy-Liuxf commented on CAPI/python/PyAPI/logic.py
> +    def GetConstructionState(self, cellX: int, cellY: int) -> THUAI7.Construction:
```suggestion
    def GetConstructionState(self, cellX: int, cellY: int) -> THUAI7.Construction | None:
```

2024-05-16 04:19 UTC, Timothy-Liuxf commented on CAPI/python/PyAPI/Interface.py
> +    def GetConstructionState(self, cellX: int, cellY: int) -> THUAI7.Construction:
```suggestion
    def GetConstructionState(self, cellX: int, cellY: int) -> THUAI7.Construction | None:
```

2024-05-16 04:19 UTC, Timothy-Liuxf commented on CAPI/python/PyAPI/Interface.py
> +    def GetConstructionState(self, cellX: int, cellY: int) -> THUAI7.Construction:
```suggestion
    def GetConstructionState(self, cellX: int, cellY: int) -> THUAI7.Construction | None:
```

2024-05-16 04:19 UTC, Timothy-Liuxf commented on CAPI/python/PyAPI/DebugAPI.py
> +    def GetConstructionState(self, cellX: int, cellY: int) -> THUAI7.Construction:
```suggestion
    def GetConstructionState(self, cellX: int, cellY: int) -> THUAI7.Construction | None:
```

2024-05-16 04:19 UTC, Timothy-Liuxf commented on CAPI/python/PyAPI/DebugAPI.py
> +    def GetConstructionState(self, cellX: int, cellY: int) -> THUAI7.Construction:
```suggestion
    def GetConstructionState(self, cellX: int, cellY: int) -> THUAI7.Construction | None:
```

2024-05-16 04:19 UTC, Timothy-Liuxf commented on CAPI/python/PyAPI/API.py
> +    def GetConstructionState(self, cellX: int, cellY: int) -> THUAI7.Construction:
```suggestion
    def GetConstructionState(self, cellX: int, cellY: int) -> THUAI7.Construction | None:
```

2024-05-16 04:19 UTC, Timothy-Liuxf commented on CAPI/python/PyAPI/API.py
> +    def GetConstructionState(self, cellX: int, cellY: int) -> THUAI7.Construction:
```suggestion
    def GetConstructionState(self, cellX: int, cellY: int) -> THUAI7.Construction | None:
```

2024-05-16 12:10 UTC, Timothy-Liuxf approved these changes

2024-05-16 12:16 UTC, merged